# Generated by Django 5.1.3 on 2024-11-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
